# Generated by Django 4.0.4 on 2022-05-29 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=1)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=1000)),
                ('question', models.CharField(max_length=1000)),
                ('student', models.CharField(max_length=1000)),
                ('Class', models.CharField(max_length=1000)),
                ('section', models.CharField(max_length=1)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 28, 42, 338281))),
                ('status', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=1000)),
                ('Class', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=1)),
                ('link', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 28, 42, 338281))),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('Class', models.CharField(blank=True, max_length=10)),
                ('section', models.CharField(blank=True, max_length=1)),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 28, 42, 338281))),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notice', models.CharField(max_length=1000)),
                ('Class', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=1)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 28, 42, 338281))),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=25)),
                ('section', models.CharField(max_length=1)),
                ('query', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 28, 42, 338281))),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=1000)),
                ('Class', models.CharField(max_length=15)),
                ('section', models.CharField(max_length=1)),
                ('question', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 28, 42, 338281))),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('authority', models.CharField(choices=[('hod', 'hod'), ('student', 'student'), ('faculty', 'faculty')], max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime(2022, 5, 29, 18, 28, 42, 337234))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=1)),
                ('regis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Design.register')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('regis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Design.register')),
            ],
        ),
    ]
