# Generated by Django 4.0.4 on 2022-05-29 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 31, 11, 515587)),
        ),
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 31, 11, 514397)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 31, 11, 516625)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 31, 11, 516625)),
        ),
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 31, 11, 516625)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 18, 31, 11, 515587)),
        ),
        migrations.AlterField(
            model_name='register',
            name='authority',
            field=models.CharField(choices=[('faculty', 'faculty'), ('hod', 'hod'), ('student', 'student')], max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 18, 31, 11, 513363)),
        ),
    ]
